config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :users, only: [:show, :edit, :update] do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :games do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :studios do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :news do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :publishers do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'mails', to: 'users#mail'

  get 'games/genre/:tag', to: 'games#index', as: :tag

  get 'announced', to: 'games#announced'
  get 'genres', to: 'games#genre'

  get 'technology', to: 'news#technology'
  get 'game', to: 'news#game'

  get :search, controller: :search
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private

    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/views/conversations/index.html.slim
title
  | Mailbox

section
  .ui.segment
    h3
      | Mailbox
    .ui.list
      .item
        - @conversations.each do |conversation|
          - if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id
            - if conversation.sender_id == current_user.id
              - recipient = User.find(conversation.recipient_id)
            - else
              - recipient = User.find(conversation.sender_id)
            = link_to recipient.username, conversation_messages_path(conversation)
            
  .ui.segment
  br
    h3
      | All Users
    .ui.list
      - @users.each do |user|
        - if user.id != current_user.id
          .item
            = image_tag(user.image.url(:small_thumb), id: "mail-pic")
            = link_to user.username, user, id: "mail-user"
            |    
            = link_to conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' do
              = image_tag ("/images/icon/send.svg")