config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :users, only: [:show, :edit, :update] do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :games do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :studios do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :news do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :publishers do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'mails', to: 'users#mail'

  get 'games/genre/:tag', to: 'games#index', as: :tag

  get 'announced', to: 'games#announced'
  get 'genres', to: 'games#genre'

  get 'technology', to: 'news#technology'
  get 'game', to: 'news#game'

  get :search, controller: :search
end

app/models/news.rb
class News < ApplicationRecord
  mount_uploader :post_pic, ImageUploader

  extend FriendlyId
  friendly_id :title, use: [ :slugged, :finders ]

  validates :title, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  def index
    @news = News.all
  end

  def show
  end

  def new
    @news = News.new
  end

  def game
    @news = News.where( option: false )
  end

  def technology
    @news = News.where( option: true )
  end

  def edit
  end

  def create
    @news = News.new(news_params)

    if @news.save
      redirect_to @news
    else
      render :new
    end
  end

  def update
    if @news.update(news_params)
      redirect_to @news
    else
      render :edit, alert: "Could not update, Please try again"
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to @news
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title, :post_pic, :news, :tag_list, :option)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.slim
= simple_form_for(@news) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    br
    = f.label :title
    br
    = f.text_field :title
    br
    br
    = f.label :post_pic
    br
    = f.file_field :post_pic
    br
    br
    = f.label :news
    br
    = f.text_area :news
    br
    br
    = f.check_box :option
    | 
    strong
      = f.label "Mark, if news about technology!~"
    br
    br
  .form-actions
    = f.button :button, "Save News", type: :submit, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."}
  br

app/views/news/edit.html.slim
title
  | Edit News

section
  h1 Change news
  - if current_user && current_user.admin
    == render 'form'

    .g-link
      p#a = link_to news_path do
            = image_tag("/images/icon/arrow-left.svg")

app/views/news/game.html.slim
title
  | Game news

section
  - @news.each do |news|
    .n-body
      .i-img
        = link_to news do
          = image_tag news.post_pic.url(:thumb)
      .n-news
        .n-title
          h2
            = link_to news do
              = news.title
        .n-text
          = news.news
    - if current_user && current_user.admin
      .g-link
        p#a = link_to news do
              = image_tag("/images/icon/search.svg")
        p#a = link_to edit_news_path(news) do
              = image_tag("/images/icon/settings.svg")
        p#a = link_to news, data: { confirm: 'Are you sure?' }, method: :delete do
              = image_tag("/images/icon/x.svg")
    br

  - if current_user && current_user.admin
    = link_to 'New News', new_news_path

app/views/news/index.html.slim
title
  | News

section
  - @news.each do |news|
    .n-body
      .i-img
        = link_to news do
          = image_tag news.post_pic.url(:thumb)
      .n-news
        .n-title
          h2
            = link_to news do
              = news.title
        .n-text
          = news.news
    - if current_user && current_user.admin
      .g-link
        p#a = link_to news do
              = image_tag("/images/icon/search.svg")
        p#a = link_to edit_news_path(news) do
              = image_tag("/images/icon/settings.svg")
        p#a = link_to news, data: { confirm: 'Are you sure?' }, method: :delete do
              = image_tag("/images/icon/x.svg")
    br

  - if current_user && current_user.admin
    = link_to 'New News', new_news_path

app/views/news/new.html.slim
title
  | New News

section
  h1 New news

  == render 'form'

  = link_to 'Back', news_index_path

app/views/news/show.html.slim
title
  | News

section
  .n-body
    .i-img
      = link_to @news do
        = image_tag @news.post_pic.url(:thumb)
    .n-news
      .n-title
        h2
          = link_to @news do
            = @news.title
      .n-text
        = @news.news
  br
    - if current_user && current_user.admin
      .g-link
        p#a = link_to edit_news_path(@news) do
              = image_tag("/images/icon/settings.svg")
        p#a = link_to news_index_path do
              = image_tag("/images/icon/arrow-left.svg")

  = render "comments/widget", commentable: @news

app/views/news/technology.html.slim
title
  | Technology

section
  - @news.each do |news|
    .n-body
      .i-img
        = link_to news do
          = image_tag news.post_pic.url(:thumb)
      .n-news
        .n-title
          h2
            = link_to news do
              = news.title
        .n-text
          = news.news
    - if current_user && current_user.admin
      .g-link
        p#a = link_to news do
              = image_tag("/images/icon/search.svg")
        p#a = link_to edit_news_path(news) do
              = image_tag("/images/icon/settings.svg")
        p#a = link_to news, data: { confirm: 'Are you sure?' }, method: :delete do
              = image_tag("/images/icon/x.svg")
    br

  - if current_user && current_user.admin
    = link_to 'New News', new_news_path