config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :users, only: [:show, :edit, :update] do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :games do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :studios do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :news do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :publishers do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'mails', to: 'users#mail'

  get 'games/genre/:tag', to: 'games#index', as: :tag

  get 'announced', to: 'games#announced'
  get 'genres', to: 'games#genre'

  get 'technology', to: 'news#technology'
  get 'game', to: 'news#game'

  get :search, controller: :search
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :studio
  belongs_to :publisher

  mount_uploader :poster, ImageUploader

  extend FriendlyId
  friendly_id :title, use: [ :slugged, :finders ]

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :tags

  validates :title, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :scores, as: :scorable, dependent: :destroy
  # has_many :user_score, dependent: :destroy

  # def average(rating)
  #   calculate(:average, rating)
  # end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag].present?
      @games = Game.tagged_with(params[:tag])
    else
      # @games = Game.all
      @games = Game.where({ release: (Time.now.midnight - 100.year)..(Time.now.midnight) })
    end
  end

  def show
    # @game.rating.average(:rating)
  end

  def new
    @game = Game.new
  end

  def genre
    @games = Game.all
  end

  def announced
    if params[:tag].present?
      @games = Game.tagged_with(params[:tag])
    else
      # @games = Game.all
      @games = Game.where({ release: (Time.now.midnight + 1.day)..(Time.now.midnight + 10.year) })
    end
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game
    else
      render :edit, alert: "Could not update, Please try again"
    end
  end

  def destroy
    @game.destroy
  end

  private

    def game_params
      params.require(:game).permit(:title, :description, :poster, :release, :genre, :tag_list, :studio_id, :publisher_id, :rating)
    end

    def set_game
      @game = Game.friendly.find(params[:id])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= simple_form_for(@game) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  br
  .form-inputs
    = f.label :title
    br
    = f.text_field :title
    br
    br
    = f.label :description
    br
    = f.text_area :description
    br
    br
    = f.label :poster
    br
    = f.file_field :poster
    br
  	br
    = f.label :release
    br
    = f.date_field :release
    br
    br
    = f.label :tag_list, "Tags (separated by commas)"
    br
    = f.text_field :tag_list
    br
    br
    = f.association :studio
    br
    = f.association :publisher
    br
  .form-actions
    = f.button :button, "Save Game", type: :submit, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."}

  br

app/views/games/_game.html.slim
section
  .g-box
    .g-all
      - @games.each do |game|
        .g-block
          .game-poster
            .g-poster
              = link_to game do
                = image_tag(game.poster.url)
                .g-info
                  .game-title = game.title
            - if current_user && current_user.admin
              .g-link
                p#a = link_to game do
                      = image_tag("/images/icon/search.svg")
                p#a = link_to edit_game_path(game) do
                      = image_tag("/images/icon/settings.svg")
                p#a = link_to game, data: { confirm: 'Are you sure?' }, method: :delete do
                      = image_tag("/images/icon/delete.svg")
          .g-sub
            #g-sub
              .game-description
                | Description:
                br
                = game.description
              br
              .game-release
                | Release
                br
                = game.release.strftime("%e %B %Y")
              br
              .game-tag
                | Genre
                br
              td
              - game.tag_list.each do |tag|
                = link_to tag, tag_path(tag: tag), id: "a"
              br
              br
              .g-studio
                | Studio
                br
                = link_to game.studio do
                  = image_tag game.studio.logotype.url(:thumb)
              .g-publisher
                | Publisher
                br
                = link_to game.publisher do
                  = image_tag game.publisher.logotype.url(:thumb)
              br

    .g-search
      span.g-srch-title
        | Advance
        br
      br
      span.g-srch-title
        | Genre
        br
      br
      .g-srch-tag
        - @games.each do |game|
          - game.tag_list.each do |tag|
            = link_to tag, tag_path(tag: tag), id: "a"
      br
  br
  - if current_user && current_user.admin
    = link_to 'New Game', new_game_path

app/views/games/_rate.html.erb
<div class="raty">
  <%= simple_form_for(@game) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <br>
    <div class="form-inputs">
      <div class="rating" data-score="<%= @game.rating %>">
    </div>
    <div class="form-actions">
      <%= f.button :button, id:"rating-submit", type: :submit, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
    </div>
  <% end %>
</div>

app/views/games/announced.html.slim
title
  | Announced

= render 'games/game'

app/views/games/edit.html.slim
title
  | Edit Game

section
  h1 Change game info
  - if current_user && current_user.admin
    == render 'form'

    .g-link
      p#a = link_to games_path do
            = image_tag("/images/icon/arrow-left.svg")

app/views/games/genre.html.slim
title
  | Genres

section
  h2 This is list of all genres
  br
  .g-all
    h3
      - @games.each do |game|
        - game.tag_list.each do |tag|
          = link_to tag, tag_path(tag: tag)
          br

app/views/games/index.html.slim
title
  | Games

= render 'games/game'

app/views/games/new.html.slim
title
  | New game
  
section
  h1 New Game

  == render 'form'

  = link_to games_path do
    = image_tag("/images/icon/arrow-left.svg")

app/views/games/show.html.slim
title
  | Games

section
  .g-all
    .g-block-show
      .game-poster
        .g-poster
          = image_tag(@game.poster.url)
        - if current_user && current_user.admin
          .link
            p#a = link_to edit_game_path(@game) do
                  = image_tag("/images/icon/settings.svg")
            p#a = link_to games_path do
                  = image_tag("/images/icon/arrow-left.svg")
      .g-info-show
        .game-title = @game.title
        br
        .game-release
          | Release
          br
          = @game.release.strftime("%e %B %Y")
        br
        .game-tag
          | Genre
          br
        td
         - @game.tag_list.each do |tag|
          = link_to tag, tag_path(tag: tag), id: "a"
         br
        br
        .game-description
          | Description:
          br
          = @game.description
        br
      .g-add-block-1
        .game-sub-img
          | Publisher
          br
          = link_to @game.publisher do
            = image_tag(@game.publisher.logotype.url(:thumb))
        .game-sub-img
          | Studio
          br
          = link_to @game.studio do
            = image_tag(@game.studio.logotype.url(:thumb))
      .g-add-block-2
        .g-rating
          #g-rating
          = render "rate"
      .g-subblock-2
  .g-add-block-3
    / .u-rating
    /   = render "scores/widget", scorable: @game
    /   #u-rating

  .comm
    = render "comments/widget", commentable: @game