config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :users, only: [:show, :edit, :update] do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :games do
    resources :scores, except: [:index, :new, :show]
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :studios do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :news do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  resources :publishers do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'mails', to: 'users#mail'

  get 'games/genre/:tag', to: 'games#index', as: :tag

  get 'announced', to: 'games#announced'
  get 'genres', to: 'games#genre'

  get 'technology', to: 'news#technology'
  get 'game', to: 'news#game'

  get :search, controller: :search
end

app/models/studio.rb
class Studio < ApplicationRecord
  mount_uploader :logotype, ImageUploader

  extend FriendlyId
  friendly_id :name, use: [ :slugged, :finders ]

  validates :name, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: [:show, :edit, :update, :destroy]

  def index
    @studios = Studio.all
  end

  def show
  end

  def new
    @studio = Studio.new
  end

  def edit
  end

  def create
    @studio = Studio.new(studio_params)

    if @studio.save
      redirect_to @studio
    else
      render :new
    end
  end

  def update
    if @studio.update(studio_params)
      redirect_to @studio
    else
      render :edit, alert: "Could not update, Please try again"
    end
  end

  def destroy
    @studio.destroy
  end

  private

    def studio_params
      params.require(:studio).permit(:name, :description, :logotype)
    end

    def set_studio
      @studio = Studio.friendly.find(params[:id])
    end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.slim
= simple_form_for(@studio) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  br
  .form-inputs
    = f.label :name
    br
    = f.text_field :name
    br
    br
    = f.label :description
    br
    = f.text_area :description
    br
    br
    = f.label :logotype
    br
    = f.file_field :logotype
    br
    br

  .form-actions
    = f.button :button, "Save Studio", type: :submit, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."}
  br

app/views/studios/edit.html.slim
title
  | Edit Studio

section
  h1 Change studio info
  - if current_user && current_user.admin
    == render 'form'

    .g-link
      p#a = link_to studios_path do
            = image_tag("/images/icon/arrow-left.svg")

app/views/studios/index.html.slim
title
  | Studios

section
  .g-all
    - @studios.each do |studio|
      .g-block
        .game-poster
          .g-poster
            = link_to studio do
              = image_tag(studio.logotype.url)
              .g-info
                .game-title = studio.name
          - if current_user && current_user.admin
            .g-link
              p#a = link_to studio do
                    = image_tag("/images/icon/search.svg")
              p#a = link_to edit_studio_path(studio) do
                    = image_tag("/images/icon/settings.svg")
              p#a = link_to studio, data: { confirm: 'Are you sure?' }, method: :delete do
                    = image_tag("/images/icon/delete.svg")
  br
  - if current_user && current_user.admin
    = link_to 'New Studio', new_studio_path

app/views/studios/new.html.slim
title
  | New Studio

section
  h1 New studio

  == render 'form'

  = link_to 'Back', studios_path

app/views/studios/show.html.slim
title
  | Studios

section
  .g-all
    .g-block-show
      .game-poster
        .g-poster
          = image_tag(@studio.logotype.url)
        - if current_user && current_user.admin
          .link
            p#a = link_to edit_studio_path(@studio) do
                  = image_tag("/images/icon/settings.svg")
            p#a = link_to studios_path do
                  = image_tag("/images/icon/arrow-left.svg")
      .g-info-show
        .game-title = @studio.name
        br
        .game-description
          | Description:
          br
          = @studio.description
        br

    = render "comments/widget", commentable: @studio